/**
 * Generated by RestExtension. Do not edit: the api exporter replaces this file.
 *
 * Builds the `filter` query parameter in the syntax QueryParser reads, for example
 * `name:[a,b],project.id:9,id:>=10`.
 */
export class ApiFilter {

    private readonly items: string[] = [];

    public where(name: string, value: unknown): ApiFilter {
        return this.whereEquals(name, typeof value === 'boolean' ? (value ? 1 : 0) : value);
    }

    public whereEquals(name: string, value: unknown): ApiFilter {
        return this.add(name, '', value);
    }

    public whereIn(name: string, values: unknown[]): ApiFilter {
        return this.whereInArray(name, values);
    }

    public whereInArray(name: string, values: unknown[]): ApiFilter {
        return this.add(name, '', `[${values.join(',')}]`);
    }

    public whereNot(name: string, value: unknown): ApiFilter {
        return this.add(name, '-', value);
    }

    public whereNotIn(name: string, values: unknown[]): ApiFilter {
        return this.add(name, '-', `[${values.join(',')}]`);
    }

    public whereGreaterThan(name: string, value: unknown): ApiFilter {
        return this.add(name, '>', value);
    }

    public whereGreaterThanOrEqual(name: string, value: unknown): ApiFilter {
        return this.add(name, '>=', value);
    }

    public whereLessThan(name: string, value: unknown): ApiFilter {
        return this.add(name, '<', value);
    }

    public whereLessThanOrEqual(name: string, value: unknown): ApiFilter {
        return this.add(name, '<=', value);
    }

    public search(name: string, value: unknown): ApiFilter {
        return this.add(name, '~', `"${String(value)}"`);
    }

    public toString(): string {
        return this.items.join(',');
    }

    private add(name: string, operand: string, value: unknown): ApiFilter {
        this.items.push(`${name}:${operand}${String(value)}`);
        return this;
    }

}
