/**
 * Generated by RestExtension. Do not edit: the api exporter replaces this file.
 *
 * Builds the `include` query parameter: relations to load with the resource.
 */
export class ApiInclude {

    private readonly items: string[] = [];

    public include(name: string): ApiInclude {
        this.items.push(name);
        return this;
    }

    public toString(): string {
        return this.items.join(',');
    }

}
