/**
 * Generated by RestExtension. Do not edit: the api exporter replaces this file.
 *
 * Builds the `ordering` query parameter, for example `name:asc,created:desc`.
 */
export class ApiOrdering {

    private readonly items: string[] = [];

    public orderBy(name: string, direction: string): ApiOrdering {
        this.items.push(`${name}:${direction}`);
        return this;
    }

    public orderAsc(name: string): ApiOrdering {
        return this.orderBy(name, 'asc');
    }

    public orderDesc(name: string): ApiOrdering {
        return this.orderBy(name, 'desc');
    }

    public toString(): string {
        return this.items.join(',');
    }

}
