/**
 * Generated by RestExtension. Do not edit: the model exporter replaces this file.
 *
 * Every model definition extends this class. It declares no members, so a definition never
 * redeclares one of them and needs no `override` under `noImplicitOverride`.
 */
export abstract class BaseModel {
}
