/**
 * Generated by RestExtension. Do not edit: the api exporter replaces this file.
 *
 * The base of every endpoint class in Api.ts, for Angular's HttpClient. Endpoints are created
 * with `new`, outside dependency injection, so the injector is handed over once at startup:
 *
 *   provideHttpClient(),
 *   provideAppInitializer(() => {
 *       ApiConfig.injector = inject(Injector);
 *       ApiConfig.baseUrl = '/api';
 *   }),
 *
 * Every request exists twice. `find$()`, `count$()`, `save$()` and `delete$()` return a typed
 * Observable, for `rxResource`, `toSignal` and RxJS operators; they need
 * `typescriptObservableMethods` in Config\RestExtension. `find()`, `count()`, `save()` and
 * `delete()` take a callback and return the Subscription. A failed callback request goes to
 * the handler from `setErrorHandler()` when there is one, and is otherwise left unhandled, so
 * Angular's global error listeners report it rather than nothing happening.
 */
import {HttpClient, HttpParams} from '@angular/common/http';
import {Injector} from '@angular/core';
import {Observable, Subscription} from 'rxjs';
import {map} from 'rxjs/operators';
import {ApiFilter} from './ApiFilter';
import {ApiInclude} from './ApiInclude';
import {ApiOrdering} from './ApiOrdering';

export class ApiConfig {

    public static injector?: Injector;

    /**
     * Put in front of every endpoint's uri, which starts with a slash.
     */
    public static baseUrl = '';

}

/**
 * The envelope a RestExtension controller answers with.
 */
interface ApiResponse {
    resource?: unknown;
    resources?: unknown[];
    count?: number;
}

export abstract class BaseApi<T = any> {

    public abstract topic: string;
    protected abstract method: string;
    protected uri = '';
    protected limitValue?: number;
    protected offsetValue?: number;

    private errorHandler?: (error: unknown) => void;
    private apiFilter?: ApiFilter;
    private apiInclude?: ApiInclude;
    private apiOrdering?: ApiOrdering;
    private readonly apiQueryParams: {key: string; value: string}[] = [];

    protected abstract convertToResource(data: any): T;

    public setErrorHandler(handler: (error: unknown) => void): this {
        this.errorHandler = handler;
        return this;
    }

    public addQueryParameter(key: string, value: unknown): this {
        this.apiQueryParams.push({key, value: String(value)});
        return this;
    }

    public getUri(): string {
        return `${ApiConfig.baseUrl}${this.uri}`;
    }

    protected filter(): ApiFilter {
        return this.apiFilter ??= new ApiFilter();
    }

    protected getInclude(): ApiInclude {
        return this.apiInclude ??= new ApiInclude();
    }

    protected ordering(): ApiOrdering {
        return this.apiOrdering ??= new ApiOrdering();
    }

    // Observable

    protected executeFind$(): Observable<T[]> {
        return this.request$('GET').pipe(map(response => this.toList(response)));
    }

    protected executeCount$(): Observable<number> {
        return this.request$('GET', undefined, {count: '1'}).pipe(map(response => response.count ?? 0));
    }

    protected executeSave$(data: unknown): Observable<T> {
        return this.request$(this.saveMethod(), data).pipe(map(response => this.toSingle(response)));
    }

    protected executeDelete$(): Observable<T> {
        return this.request$('DELETE').pipe(map(response => this.toSingle(response)));
    }

    protected executeClientGet(): Observable<T[]> {
        return this.executeFind$();
    }

    // Callback

    protected executeFind(next?: (value: T[]) => void): Subscription {
        return this.subscribe(this.executeFind$(), next);
    }

    protected executeCount(next?: (value: number) => void): Subscription {
        return this.subscribe(this.executeCount$(), next);
    }

    protected executeSave(data: unknown, next?: (value: T) => void): Subscription {
        return this.subscribe(this.executeSave$(data), next);
    }

    protected executeDelete(next?: (value: T) => void): Subscription {
        return this.subscribe(this.executeDelete$(), next);
    }

    // Internals

    private subscribe<R>(source: Observable<R>, next?: (value: R) => void): Subscription {
        const handler = this.errorHandler;
        return source.subscribe(handler
            ? {next: value => next?.(value), error: (error: unknown) => handler(error)}
            : {next: value => next?.(value)});
    }

    private request$(method: string, body?: unknown, extra: Record<string, string> = {}): Observable<ApiResponse> {
        if (!ApiConfig.injector) {
            throw new Error('RestExtension: set ApiConfig.injector at startup before calling the api');
        }
        return ApiConfig.injector.get(HttpClient).request<ApiResponse>(method, this.getUri(), {
            body,
            params: this.params(extra),
        });
    }

    private saveMethod(): string {
        switch (this.method) {
            case 'post':
            case 'restore':
                return 'POST';
            case 'put':
                return 'PUT';
            case 'patch':
                return 'PATCH';
            default:
                throw new Error(`RestExtension: ${this.method} is not a method that saves`);
        }
    }

    private params(extra: Record<string, string>): HttpParams {
        let params = new HttpParams({fromObject: extra});
        for (const {key, value} of this.apiQueryParams) {
            params = params.append(key, value);
        }
        if (this.apiFilter) params = params.append('filter', this.apiFilter.toString());
        if (this.apiInclude) params = params.append('include', this.apiInclude.toString());
        if (this.apiOrdering) params = params.append('ordering', this.apiOrdering.toString());
        if (this.limitValue !== undefined && this.limitValue >= 0) params = params.append('limit', this.limitValue);
        if (this.offsetValue !== undefined) params = params.append('offset', this.offsetValue);
        return params;
    }

    private toList(response: ApiResponse): T[] {
        if (response.resources) return response.resources.map(resource => this.convertToResource(resource));
        if (response.resource !== undefined) return [this.convertToResource(response.resource)];
        return [];
    }

    /**
     * A save or delete answers with one resource. An endpoint declared without a response
     * schema is typed `any` and may answer with a list, or with nothing.
     */
    private toSingle(response: ApiResponse): T {
        if (response.resource !== undefined) return this.convertToResource(response.resource);
        if (response.resources) return response.resources.map(resource => this.convertToResource(resource)) as unknown as T;
        return undefined as unknown as T;
    }

}
